-- NOCTUA PENDING CHANGES
-- Todos los SQL nuevos irán aquí antes de ejecutarlos

-- Ejemplo:
--
-- alter table clubs
-- add column instagram text;
-- Crear tabla para noches/eventos propios de clubs

create table if not exists club_events (
  id bigint generated by default as identity primary key,
  club_id bigint references clubs(id) on delete cascade,
  club_name text,
  title text not null,
  artist text,
  music text,
  date date,
  start_time text,
  end_time text,
  price text,
  ticket_url text,
  image text,
  description text,
  featured boolean default false,
  sold_out boolean default false,
  created_at timestamp with time zone default now()
);

alter table club_events enable row level security;

create policy "Allow public read club_events"
on club_events
for select
using (true);

create policy "Allow admin insert club_events"
on club_events
for insert
to authenticated
with check (auth.email() = 'info@noctuaapp.com');

create policy "Allow admin update club_events"
on club_events
for update
to authenticated
using (auth.email() = 'info@noctuaapp.com')
with check (auth.email() = 'info@noctuaapp.com');

create policy "Allow admin delete club_events"
on club_events
for delete
to authenticated
using (auth.email() = 'info@noctuaapp.com');
alter table tickets
add column if not exists club_event_id bigint references club_events(id) on delete cascade;
create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  item_type text not null check (item_type in ('club', 'event', 'club_event')),
  item_id bigint not null,
  created_at timestamp with time zone default now(),
  unique(user_id, item_type, item_id)
);

alter table favorites enable row level security;

create policy "Users can read own favorites"
on favorites
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own favorites"
on favorites
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can delete own favorites"
on favorites
for delete
to authenticated
using (auth.uid() = user_id);