// Generado a partir de umpirsky/country-list (datos ISO 3166 con nombre por idioma),
// para el selector de país del registro y del admin. Incluye países y territorios
// autónomos (p. ej. Hong Kong, Puerto Rico) además de los estados soberanos, porque
// un usuario puede identificarse con cualquiera de ellos como "de dónde es".
export type CountryLocale = "es" | "en" | "ca" | "fr" | "de" | "it" | "nl"

export type Country = {
  code: string
  flag: string
  es: string
  en: string
  ca: string
  fr: string
  de: string
  it: string
  nl: string
}

export const COUNTRIES: Country[] = [
  { code: "AD", flag: "🇦🇩", es: "Andorra", en: "Andorra", ca: "Andorra", fr: "Andorre", de: "Andorra", it: "Andorra", nl: "Andorra" },
  { code: "AE", flag: "🇦🇪", es: "Emiratos Árabes Unidos", en: "United Arab Emirates", ca: "Emirats Àrabs Units", fr: "Émirats arabes unis", de: "Vereinigte Arabische Emirate", it: "Emirati Arabi Uniti", nl: "Verenigde Arabische Emiraten" },
  { code: "AF", flag: "🇦🇫", es: "Afganistán", en: "Afghanistan", ca: "Afganistan", fr: "Afghanistan", de: "Afghanistan", it: "Afghanistan", nl: "Afghanistan" },
  { code: "AG", flag: "🇦🇬", es: "Antigua y Barbuda", en: "Antigua & Barbuda", ca: "Antigua i Barbuda", fr: "Antigua-et-Barbuda", de: "Antigua und Barbuda", it: "Antigua e Barbuda", nl: "Antigua en Barbuda" },
  { code: "AI", flag: "🇦🇮", es: "Anguila", en: "Anguilla", ca: "Anguilla", fr: "Anguilla", de: "Anguilla", it: "Anguilla", nl: "Anguilla" },
  { code: "AL", flag: "🇦🇱", es: "Albania", en: "Albania", ca: "Albània", fr: "Albanie", de: "Albanien", it: "Albania", nl: "Albanië" },
  { code: "AM", flag: "🇦🇲", es: "Armenia", en: "Armenia", ca: "Armènia", fr: "Arménie", de: "Armenien", it: "Armenia", nl: "Armenië" },
  { code: "AO", flag: "🇦🇴", es: "Angola", en: "Angola", ca: "Angola", fr: "Angola", de: "Angola", it: "Angola", nl: "Angola" },
  { code: "AQ", flag: "🇦🇶", es: "Antártida", en: "Antarctica", ca: "Antàrtida", fr: "Antarctique", de: "Antarktis", it: "Antartide", nl: "Antarctica" },
  { code: "AR", flag: "🇦🇷", es: "Argentina", en: "Argentina", ca: "Argentina", fr: "Argentine", de: "Argentinien", it: "Argentina", nl: "Argentinië" },
  { code: "AS", flag: "🇦🇸", es: "Samoa Americana", en: "American Samoa", ca: "Samoa Nord-americana", fr: "Samoa américaines", de: "Amerikanisch-Samoa", it: "Samoa americane", nl: "Amerikaans-Samoa" },
  { code: "AT", flag: "🇦🇹", es: "Austria", en: "Austria", ca: "Àustria", fr: "Autriche", de: "Österreich", it: "Austria", nl: "Oostenrijk" },
  { code: "AU", flag: "🇦🇺", es: "Australia", en: "Australia", ca: "Austràlia", fr: "Australie", de: "Australien", it: "Australia", nl: "Australië" },
  { code: "AW", flag: "🇦🇼", es: "Aruba", en: "Aruba", ca: "Aruba", fr: "Aruba", de: "Aruba", it: "Aruba", nl: "Aruba" },
  { code: "AX", flag: "🇦🇽", es: "Islas Åland", en: "Åland Islands", ca: "Illes Åland", fr: "Îles Åland", de: "Ålandinseln", it: "Isole Åland", nl: "Åland" },
  { code: "AZ", flag: "🇦🇿", es: "Azerbaiyán", en: "Azerbaijan", ca: "Azerbaidjan", fr: "Azerbaïdjan", de: "Aserbaidschan", it: "Azerbaigian", nl: "Azerbeidzjan" },
  { code: "BA", flag: "🇧🇦", es: "Bosnia y Herzegovina", en: "Bosnia & Herzegovina", ca: "Bòsnia i Hercegovina", fr: "Bosnie-Herzégovine", de: "Bosnien und Herzegowina", it: "Bosnia ed Erzegovina", nl: "Bosnië en Herzegovina" },
  { code: "BB", flag: "🇧🇧", es: "Barbados", en: "Barbados", ca: "Barbados", fr: "Barbade", de: "Barbados", it: "Barbados", nl: "Barbados" },
  { code: "BD", flag: "🇧🇩", es: "Bangladés", en: "Bangladesh", ca: "Bangladesh", fr: "Bangladesh", de: "Bangladesch", it: "Bangladesh", nl: "Bangladesh" },
  { code: "BE", flag: "🇧🇪", es: "Bélgica", en: "Belgium", ca: "Bèlgica", fr: "Belgique", de: "Belgien", it: "Belgio", nl: "België" },
  { code: "BF", flag: "🇧🇫", es: "Burkina Faso", en: "Burkina Faso", ca: "Burkina Faso", fr: "Burkina Faso", de: "Burkina Faso", it: "Burkina Faso", nl: "Burkina Faso" },
  { code: "BG", flag: "🇧🇬", es: "Bulgaria", en: "Bulgaria", ca: "Bulgària", fr: "Bulgarie", de: "Bulgarien", it: "Bulgaria", nl: "Bulgarije" },
  { code: "BH", flag: "🇧🇭", es: "Baréin", en: "Bahrain", ca: "Bahrain", fr: "Bahreïn", de: "Bahrain", it: "Bahrein", nl: "Bahrein" },
  { code: "BI", flag: "🇧🇮", es: "Burundi", en: "Burundi", ca: "Burundi", fr: "Burundi", de: "Burundi", it: "Burundi", nl: "Burundi" },
  { code: "BJ", flag: "🇧🇯", es: "Benín", en: "Benin", ca: "Benín", fr: "Bénin", de: "Benin", it: "Benin", nl: "Benin" },
  { code: "BL", flag: "🇧🇱", es: "San Bartolomé", en: "St. Barthélemy", ca: "Saint Barthélemy", fr: "Saint-Barthélemy", de: "St. Barthélemy", it: "Saint-Barthélemy", nl: "Saint-Barthélemy" },
  { code: "BM", flag: "🇧🇲", es: "Bermudas", en: "Bermuda", ca: "Bermudes", fr: "Bermudes", de: "Bermuda", it: "Bermuda", nl: "Bermuda" },
  { code: "BN", flag: "🇧🇳", es: "Brunéi", en: "Brunei", ca: "Brunei", fr: "Brunéi Darussalam", de: "Brunei Darussalam", it: "Brunei", nl: "Brunei" },
  { code: "BO", flag: "🇧🇴", es: "Bolivia", en: "Bolivia", ca: "Bolívia", fr: "Bolivie", de: "Bolivien", it: "Bolivia", nl: "Bolivia" },
  { code: "BQ", flag: "🇧🇶", es: "Caribe neerlandés", en: "Caribbean Netherlands", ca: "Carib Neerlandès", fr: "Pays-Bas caribéens", de: "Bonaire, Sint Eustatius und Saba", it: "Caraibi olandesi", nl: "Caribisch Nederland" },
  { code: "BR", flag: "🇧🇷", es: "Brasil", en: "Brazil", ca: "Brasil", fr: "Brésil", de: "Brasilien", it: "Brasile", nl: "Brazilië" },
  { code: "BS", flag: "🇧🇸", es: "Bahamas", en: "Bahamas", ca: "Bahames", fr: "Bahamas", de: "Bahamas", it: "Bahamas", nl: "Bahama’s" },
  { code: "BT", flag: "🇧🇹", es: "Bután", en: "Bhutan", ca: "Bhutan", fr: "Bhoutan", de: "Bhutan", it: "Bhutan", nl: "Bhutan" },
  { code: "BV", flag: "🇧🇻", es: "Isla Bouvet", en: "Bouvet Island", ca: "Bouvet", fr: "Île Bouvet", de: "Bouvetinsel", it: "Isola Bouvet", nl: "Bouveteiland" },
  { code: "BW", flag: "🇧🇼", es: "Botsuana", en: "Botswana", ca: "Botswana", fr: "Botswana", de: "Botsuana", it: "Botswana", nl: "Botswana" },
  { code: "BY", flag: "🇧🇾", es: "Bielorrusia", en: "Belarus", ca: "Belarús", fr: "Biélorussie", de: "Belarus", it: "Bielorussia", nl: "Belarus" },
  { code: "BZ", flag: "🇧🇿", es: "Belice", en: "Belize", ca: "Belize", fr: "Belize", de: "Belize", it: "Belize", nl: "Belize" },
  { code: "CA", flag: "🇨🇦", es: "Canadá", en: "Canada", ca: "Canadà", fr: "Canada", de: "Kanada", it: "Canada", nl: "Canada" },
  { code: "CC", flag: "🇨🇨", es: "Islas Cocos", en: "Cocos (Keeling) Islands", ca: "Illes Cocos", fr: "Îles Cocos", de: "Kokosinseln", it: "Isole Cocos (Keeling)", nl: "Cocoseilanden" },
  { code: "CD", flag: "🇨🇩", es: "República Democrática del Congo", en: "Congo - Kinshasa", ca: "Congo - Kinshasa", fr: "Congo-Kinshasa", de: "Kongo-Kinshasa", it: "Congo - Kinshasa", nl: "Congo-Kinshasa" },
  { code: "CF", flag: "🇨🇫", es: "República Centroafricana", en: "Central African Republic", ca: "República Centreafricana", fr: "République centrafricaine", de: "Zentralafrikanische Republik", it: "Repubblica Centrafricana", nl: "Centraal-Afrikaanse Republiek" },
  { code: "CG", flag: "🇨🇬", es: "Congo", en: "Congo - Brazzaville", ca: "Congo - Brazzaville", fr: "Congo-Brazzaville", de: "Kongo-Brazzaville", it: "Congo-Brazzaville", nl: "Congo-Brazzaville" },
  { code: "CH", flag: "🇨🇭", es: "Suiza", en: "Switzerland", ca: "Suïssa", fr: "Suisse", de: "Schweiz", it: "Svizzera", nl: "Zwitserland" },
  { code: "CI", flag: "🇨🇮", es: "Côte d’Ivoire", en: "Côte d’Ivoire", ca: "Côte d’Ivoire", fr: "Côte d’Ivoire", de: "Côte d’Ivoire", it: "Costa d’Avorio", nl: "Ivoorkust" },
  { code: "CK", flag: "🇨🇰", es: "Islas Cook", en: "Cook Islands", ca: "Illes Cook", fr: "Îles Cook", de: "Cookinseln", it: "Isole Cook", nl: "Cookeilanden" },
  { code: "CL", flag: "🇨🇱", es: "Chile", en: "Chile", ca: "Xile", fr: "Chili", de: "Chile", it: "Cile", nl: "Chili" },
  { code: "CM", flag: "🇨🇲", es: "Camerún", en: "Cameroon", ca: "Camerun", fr: "Cameroun", de: "Kamerun", it: "Camerun", nl: "Kameroen" },
  { code: "CN", flag: "🇨🇳", es: "China", en: "China", ca: "Xina", fr: "Chine", de: "China", it: "Cina", nl: "China" },
  { code: "CO", flag: "🇨🇴", es: "Colombia", en: "Colombia", ca: "Colòmbia", fr: "Colombie", de: "Kolumbien", it: "Colombia", nl: "Colombia" },
  { code: "CR", flag: "🇨🇷", es: "Costa Rica", en: "Costa Rica", ca: "Costa Rica", fr: "Costa Rica", de: "Costa Rica", it: "Costa Rica", nl: "Costa Rica" },
  { code: "CU", flag: "🇨🇺", es: "Cuba", en: "Cuba", ca: "Cuba", fr: "Cuba", de: "Kuba", it: "Cuba", nl: "Cuba" },
  { code: "CV", flag: "🇨🇻", es: "Cabo Verde", en: "Cape Verde", ca: "Cap Verd", fr: "Cap-Vert", de: "Cabo Verde", it: "Capo Verde", nl: "Kaapverdië" },
  { code: "CW", flag: "🇨🇼", es: "Curazao", en: "Curaçao", ca: "Curaçao", fr: "Curaçao", de: "Curaçao", it: "Curaçao", nl: "Curaçao" },
  { code: "CX", flag: "🇨🇽", es: "Isla de Navidad", en: "Christmas Island", ca: "Illa Christmas", fr: "Île Christmas", de: "Weihnachtsinsel", it: "Isola Christmas", nl: "Christmaseiland" },
  { code: "CY", flag: "🇨🇾", es: "Chipre", en: "Cyprus", ca: "Xipre", fr: "Chypre", de: "Zypern", it: "Cipro", nl: "Cyprus" },
  { code: "CZ", flag: "🇨🇿", es: "Chequia", en: "Czechia", ca: "Txèquia", fr: "Tchéquie", de: "Tschechien", it: "Cechia", nl: "Tsjechië" },
  { code: "DE", flag: "🇩🇪", es: "Alemania", en: "Germany", ca: "Alemanya", fr: "Allemagne", de: "Deutschland", it: "Germania", nl: "Duitsland" },
  { code: "DJ", flag: "🇩🇯", es: "Yibuti", en: "Djibouti", ca: "Djibouti", fr: "Djibouti", de: "Dschibuti", it: "Gibuti", nl: "Djibouti" },
  { code: "DK", flag: "🇩🇰", es: "Dinamarca", en: "Denmark", ca: "Dinamarca", fr: "Danemark", de: "Dänemark", it: "Danimarca", nl: "Denemarken" },
  { code: "DM", flag: "🇩🇲", es: "Dominica", en: "Dominica", ca: "Dominica", fr: "Dominique", de: "Dominica", it: "Dominica", nl: "Dominica" },
  { code: "DO", flag: "🇩🇴", es: "República Dominicana", en: "Dominican Republic", ca: "República Dominicana", fr: "République dominicaine", de: "Dominikanische Republik", it: "Repubblica Dominicana", nl: "Dominicaanse Republiek" },
  { code: "DZ", flag: "🇩🇿", es: "Argelia", en: "Algeria", ca: "Algèria", fr: "Algérie", de: "Algerien", it: "Algeria", nl: "Algerije" },
  { code: "EC", flag: "🇪🇨", es: "Ecuador", en: "Ecuador", ca: "Equador", fr: "Équateur", de: "Ecuador", it: "Ecuador", nl: "Ecuador" },
  { code: "EE", flag: "🇪🇪", es: "Estonia", en: "Estonia", ca: "Estònia", fr: "Estonie", de: "Estland", it: "Estonia", nl: "Estland" },
  { code: "EG", flag: "🇪🇬", es: "Egipto", en: "Egypt", ca: "Egipte", fr: "Égypte", de: "Ägypten", it: "Egitto", nl: "Egypte" },
  { code: "EH", flag: "🇪🇭", es: "Sáhara Occidental", en: "Western Sahara", ca: "Sàhara Occidental", fr: "Sahara occidental", de: "Westsahara", it: "Sahara occidentale", nl: "Westelijke Sahara" },
  { code: "ER", flag: "🇪🇷", es: "Eritrea", en: "Eritrea", ca: "Eritrea", fr: "Érythrée", de: "Eritrea", it: "Eritrea", nl: "Eritrea" },
  { code: "ES", flag: "🇪🇸", es: "España", en: "Spain", ca: "Espanya", fr: "Espagne", de: "Spanien", it: "Spagna", nl: "Spanje" },
  { code: "ET", flag: "🇪🇹", es: "Etiopía", en: "Ethiopia", ca: "Etiòpia", fr: "Éthiopie", de: "Äthiopien", it: "Etiopia", nl: "Ethiopië" },
  { code: "FI", flag: "🇫🇮", es: "Finlandia", en: "Finland", ca: "Finlàndia", fr: "Finlande", de: "Finnland", it: "Finlandia", nl: "Finland" },
  { code: "FJ", flag: "🇫🇯", es: "Fiyi", en: "Fiji", ca: "Fiji", fr: "Fidji", de: "Fidschi", it: "Figi", nl: "Fiji" },
  { code: "FK", flag: "🇫🇰", es: "Islas Malvinas", en: "Falkland Islands", ca: "Illes Malvines", fr: "Îles Malouines", de: "Falklandinseln", it: "Isole Falkland", nl: "Falklandeilanden" },
  { code: "FM", flag: "🇫🇲", es: "Micronesia", en: "Micronesia", ca: "Micronèsia", fr: "États fédérés de Micronésie", de: "Mikronesien", it: "Micronesia", nl: "Micronesia" },
  { code: "FO", flag: "🇫🇴", es: "Islas Feroe", en: "Faroe Islands", ca: "Illes Fèroe", fr: "Îles Féroé", de: "Färöer", it: "Isole Fær Øer", nl: "Faeröer" },
  { code: "FR", flag: "🇫🇷", es: "Francia", en: "France", ca: "França", fr: "France", de: "Frankreich", it: "Francia", nl: "Frankrijk" },
  { code: "GA", flag: "🇬🇦", es: "Gabón", en: "Gabon", ca: "Gabon", fr: "Gabon", de: "Gabun", it: "Gabon", nl: "Gabon" },
  { code: "GB", flag: "🇬🇧", es: "Reino Unido", en: "United Kingdom", ca: "Regne Unit", fr: "Royaume-Uni", de: "Vereinigtes Königreich", it: "Regno Unito", nl: "Verenigd Koninkrijk" },
  { code: "GD", flag: "🇬🇩", es: "Granada", en: "Grenada", ca: "Grenada", fr: "Grenade", de: "Grenada", it: "Grenada", nl: "Grenada" },
  { code: "GE", flag: "🇬🇪", es: "Georgia", en: "Georgia", ca: "Geòrgia", fr: "Géorgie", de: "Georgien", it: "Georgia", nl: "Georgië" },
  { code: "GF", flag: "🇬🇫", es: "Guayana Francesa", en: "French Guiana", ca: "Guaiana Francesa", fr: "Guyane française", de: "Französisch-Guayana", it: "Guyana francese", nl: "Frans-Guyana" },
  { code: "GG", flag: "🇬🇬", es: "Guernsey", en: "Guernsey", ca: "Guernsey", fr: "Guernesey", de: "Guernsey", it: "Guernsey", nl: "Guernsey" },
  { code: "GH", flag: "🇬🇭", es: "Ghana", en: "Ghana", ca: "Ghana", fr: "Ghana", de: "Ghana", it: "Ghana", nl: "Ghana" },
  { code: "GI", flag: "🇬🇮", es: "Gibraltar", en: "Gibraltar", ca: "Gibraltar", fr: "Gibraltar", de: "Gibraltar", it: "Gibilterra", nl: "Gibraltar" },
  { code: "GL", flag: "🇬🇱", es: "Groenlandia", en: "Greenland", ca: "Groenlàndia", fr: "Groenland", de: "Grönland", it: "Groenlandia", nl: "Groenland" },
  { code: "GM", flag: "🇬🇲", es: "Gambia", en: "Gambia", ca: "Gàmbia", fr: "Gambie", de: "Gambia", it: "Gambia", nl: "Gambia" },
  { code: "GN", flag: "🇬🇳", es: "Guinea", en: "Guinea", ca: "Guinea", fr: "Guinée", de: "Guinea", it: "Guinea", nl: "Guinee" },
  { code: "GP", flag: "🇬🇵", es: "Guadalupe", en: "Guadeloupe", ca: "Guadeloupe", fr: "Guadeloupe", de: "Guadeloupe", it: "Guadalupa", nl: "Guadeloupe" },
  { code: "GQ", flag: "🇬🇶", es: "Guinea Ecuatorial", en: "Equatorial Guinea", ca: "Guinea Equatorial", fr: "Guinée équatoriale", de: "Äquatorialguinea", it: "Guinea Equatoriale", nl: "Equatoriaal-Guinea" },
  { code: "GR", flag: "🇬🇷", es: "Grecia", en: "Greece", ca: "Grècia", fr: "Grèce", de: "Griechenland", it: "Grecia", nl: "Griekenland" },
  { code: "GS", flag: "🇬🇸", es: "Islas Georgia del Sur y Sandwich del Sur", en: "South Georgia & South Sandwich Islands", ca: "Illes Geòrgia del Sud i Sandwich del Sud", fr: "Géorgie du Sud et îles Sandwich du Sud", de: "Südgeorgien und die Südlichen Sandwichinseln", it: "Georgia del Sud e Sandwich australi", nl: "Zuid-Georgia en Zuidelijke Sandwicheilanden" },
  { code: "GT", flag: "🇬🇹", es: "Guatemala", en: "Guatemala", ca: "Guatemala", fr: "Guatemala", de: "Guatemala", it: "Guatemala", nl: "Guatemala" },
  { code: "GU", flag: "🇬🇺", es: "Guam", en: "Guam", ca: "Guam", fr: "Guam", de: "Guam", it: "Guam", nl: "Guam" },
  { code: "GW", flag: "🇬🇼", es: "Guinea-Bisáu", en: "Guinea-Bissau", ca: "Guinea Bissau", fr: "Guinée-Bissau", de: "Guinea-Bissau", it: "Guinea-Bissau", nl: "Guinee-Bissau" },
  { code: "GY", flag: "🇬🇾", es: "Guyana", en: "Guyana", ca: "Guyana", fr: "Guyana", de: "Guyana", it: "Guyana", nl: "Guyana" },
  { code: "HK", flag: "🇭🇰", es: "RAE de Hong Kong (China)", en: "Hong Kong SAR China", ca: "Hong Kong (RAE Xina)", fr: "R.A.S. chinoise de Hong Kong", de: "Sonderverwaltungsregion Hongkong", it: "RAS di Hong Kong", nl: "Hongkong SAR van China" },
  { code: "HM", flag: "🇭🇲", es: "Islas Heard y McDonald", en: "Heard & McDonald Islands", ca: "Illa Heard i Illes McDonald", fr: "Îles Heard et McDonald", de: "Heard und McDonaldinseln", it: "Isole Heard e McDonald", nl: "Heard en McDonaldeilanden" },
  { code: "HN", flag: "🇭🇳", es: "Honduras", en: "Honduras", ca: "Hondures", fr: "Honduras", de: "Honduras", it: "Honduras", nl: "Honduras" },
  { code: "HR", flag: "🇭🇷", es: "Croacia", en: "Croatia", ca: "Croàcia", fr: "Croatie", de: "Kroatien", it: "Croazia", nl: "Kroatië" },
  { code: "HT", flag: "🇭🇹", es: "Haití", en: "Haiti", ca: "Haití", fr: "Haïti", de: "Haiti", it: "Haiti", nl: "Haïti" },
  { code: "HU", flag: "🇭🇺", es: "Hungría", en: "Hungary", ca: "Hongria", fr: "Hongrie", de: "Ungarn", it: "Ungheria", nl: "Hongarije" },
  { code: "ID", flag: "🇮🇩", es: "Indonesia", en: "Indonesia", ca: "Indonèsia", fr: "Indonésie", de: "Indonesien", it: "Indonesia", nl: "Indonesië" },
  { code: "IE", flag: "🇮🇪", es: "Irlanda", en: "Ireland", ca: "Irlanda", fr: "Irlande", de: "Irland", it: "Irlanda", nl: "Ierland" },
  { code: "IL", flag: "🇮🇱", es: "Israel", en: "Israel", ca: "Israel", fr: "Israël", de: "Israel", it: "Israele", nl: "Israël" },
  { code: "IM", flag: "🇮🇲", es: "Isla de Man", en: "Isle of Man", ca: "Illa de Man", fr: "Île de Man", de: "Isle of Man", it: "Isola di Man", nl: "Isle of Man" },
  { code: "IN", flag: "🇮🇳", es: "India", en: "India", ca: "Índia", fr: "Inde", de: "Indien", it: "India", nl: "India" },
  { code: "IO", flag: "🇮🇴", es: "Territorio Británico del Océano Índico", en: "British Indian Ocean Territory", ca: "Territori Britànic de l’Oceà Índic", fr: "Territoire britannique de l’océan Indien", de: "Britisches Territorium im Indischen Ozean", it: "Territorio britannico dell’Oceano Indiano", nl: "Brits Indische Oceaanterritorium" },
  { code: "IQ", flag: "🇮🇶", es: "Irak", en: "Iraq", ca: "Iraq", fr: "Irak", de: "Irak", it: "Iraq", nl: "Irak" },
  { code: "IR", flag: "🇮🇷", es: "Irán", en: "Iran", ca: "Iran", fr: "Iran", de: "Iran", it: "Iran", nl: "Iran" },
  { code: "IS", flag: "🇮🇸", es: "Islandia", en: "Iceland", ca: "Islàndia", fr: "Islande", de: "Island", it: "Islanda", nl: "IJsland" },
  { code: "IT", flag: "🇮🇹", es: "Italia", en: "Italy", ca: "Itàlia", fr: "Italie", de: "Italien", it: "Italia", nl: "Italië" },
  { code: "JE", flag: "🇯🇪", es: "Jersey", en: "Jersey", ca: "Jersey", fr: "Jersey", de: "Jersey", it: "Jersey", nl: "Jersey" },
  { code: "JM", flag: "🇯🇲", es: "Jamaica", en: "Jamaica", ca: "Jamaica", fr: "Jamaïque", de: "Jamaika", it: "Giamaica", nl: "Jamaica" },
  { code: "JO", flag: "🇯🇴", es: "Jordania", en: "Jordan", ca: "Jordània", fr: "Jordanie", de: "Jordanien", it: "Giordania", nl: "Jordanië" },
  { code: "JP", flag: "🇯🇵", es: "Japón", en: "Japan", ca: "Japó", fr: "Japon", de: "Japan", it: "Giappone", nl: "Japan" },
  { code: "KE", flag: "🇰🇪", es: "Kenia", en: "Kenya", ca: "Kenya", fr: "Kenya", de: "Kenia", it: "Kenya", nl: "Kenia" },
  { code: "KG", flag: "🇰🇬", es: "Kirguistán", en: "Kyrgyzstan", ca: "Kirguizistan", fr: "Kirghizistan", de: "Kirgisistan", it: "Kirghizistan", nl: "Kirgizië" },
  { code: "KH", flag: "🇰🇭", es: "Camboya", en: "Cambodia", ca: "Cambodja", fr: "Cambodge", de: "Kambodscha", it: "Cambogia", nl: "Cambodja" },
  { code: "KI", flag: "🇰🇮", es: "Kiribati", en: "Kiribati", ca: "Kiribati", fr: "Kiribati", de: "Kiribati", it: "Kiribati", nl: "Kiribati" },
  { code: "KM", flag: "🇰🇲", es: "Comoras", en: "Comoros", ca: "Comores", fr: "Comores", de: "Komoren", it: "Comore", nl: "Comoren" },
  { code: "KN", flag: "🇰🇳", es: "San Cristóbal y Nieves", en: "St. Kitts & Nevis", ca: "Saint Christopher i Nevis", fr: "Saint-Christophe-et-Niévès", de: "St. Kitts und Nevis", it: "Saint Kitts e Nevis", nl: "Saint Kitts en Nevis" },
  { code: "KP", flag: "🇰🇵", es: "Corea del Norte", en: "North Korea", ca: "Corea del Nord", fr: "Corée du Nord", de: "Nordkorea", it: "Corea del Nord", nl: "Noord-Korea" },
  { code: "KR", flag: "🇰🇷", es: "Corea del Sur", en: "South Korea", ca: "Corea del Sud", fr: "Corée du Sud", de: "Südkorea", it: "Corea del Sud", nl: "Zuid-Korea" },
  { code: "KW", flag: "🇰🇼", es: "Kuwait", en: "Kuwait", ca: "Kuwait", fr: "Koweït", de: "Kuwait", it: "Kuwait", nl: "Koeweit" },
  { code: "KY", flag: "🇰🇾", es: "Islas Caimán", en: "Cayman Islands", ca: "Illes Caiman", fr: "Îles Caïmans", de: "Kaimaninseln", it: "Isole Cayman", nl: "Kaaimaneilanden" },
  { code: "KZ", flag: "🇰🇿", es: "Kazajistán", en: "Kazakhstan", ca: "Kazakhstan", fr: "Kazakhstan", de: "Kasachstan", it: "Kazakistan", nl: "Kazachstan" },
  { code: "LA", flag: "🇱🇦", es: "Laos", en: "Laos", ca: "Laos", fr: "Laos", de: "Laos", it: "Laos", nl: "Laos" },
  { code: "LB", flag: "🇱🇧", es: "Líbano", en: "Lebanon", ca: "Líban", fr: "Liban", de: "Libanon", it: "Libano", nl: "Libanon" },
  { code: "LC", flag: "🇱🇨", es: "Santa Lucía", en: "St. Lucia", ca: "Saint Lucia", fr: "Sainte-Lucie", de: "St. Lucia", it: "Saint Lucia", nl: "Saint Lucia" },
  { code: "LI", flag: "🇱🇮", es: "Liechtenstein", en: "Liechtenstein", ca: "Liechtenstein", fr: "Liechtenstein", de: "Liechtenstein", it: "Liechtenstein", nl: "Liechtenstein" },
  { code: "LK", flag: "🇱🇰", es: "Sri Lanka", en: "Sri Lanka", ca: "Sri Lanka", fr: "Sri Lanka", de: "Sri Lanka", it: "Sri Lanka", nl: "Sri Lanka" },
  { code: "LR", flag: "🇱🇷", es: "Liberia", en: "Liberia", ca: "Libèria", fr: "Libéria", de: "Liberia", it: "Liberia", nl: "Liberia" },
  { code: "LS", flag: "🇱🇸", es: "Lesoto", en: "Lesotho", ca: "Lesotho", fr: "Lesotho", de: "Lesotho", it: "Lesotho", nl: "Lesotho" },
  { code: "LT", flag: "🇱🇹", es: "Lituania", en: "Lithuania", ca: "Lituània", fr: "Lituanie", de: "Litauen", it: "Lituania", nl: "Litouwen" },
  { code: "LU", flag: "🇱🇺", es: "Luxemburgo", en: "Luxembourg", ca: "Luxemburg", fr: "Luxembourg", de: "Luxemburg", it: "Lussemburgo", nl: "Luxemburg" },
  { code: "LV", flag: "🇱🇻", es: "Letonia", en: "Latvia", ca: "Letònia", fr: "Lettonie", de: "Lettland", it: "Lettonia", nl: "Letland" },
  { code: "LY", flag: "🇱🇾", es: "Libia", en: "Libya", ca: "Líbia", fr: "Libye", de: "Libyen", it: "Libia", nl: "Libië" },
  { code: "MA", flag: "🇲🇦", es: "Marruecos", en: "Morocco", ca: "Marroc", fr: "Maroc", de: "Marokko", it: "Marocco", nl: "Marokko" },
  { code: "MC", flag: "🇲🇨", es: "Mónaco", en: "Monaco", ca: "Mònaco", fr: "Monaco", de: "Monaco", it: "Monaco", nl: "Monaco" },
  { code: "MD", flag: "🇲🇩", es: "Moldavia", en: "Moldova", ca: "Moldàvia", fr: "Moldavie", de: "Republik Moldau", it: "Moldavia", nl: "Moldavië" },
  { code: "ME", flag: "🇲🇪", es: "Montenegro", en: "Montenegro", ca: "Montenegro", fr: "Monténégro", de: "Montenegro", it: "Montenegro", nl: "Montenegro" },
  { code: "MF", flag: "🇲🇫", es: "San Martín", en: "St. Martin", ca: "Saint Martin", fr: "Saint-Martin", de: "St. Martin", it: "Saint Martin", nl: "Saint-Martin" },
  { code: "MG", flag: "🇲🇬", es: "Madagascar", en: "Madagascar", ca: "Madagascar", fr: "Madagascar", de: "Madagaskar", it: "Madagascar", nl: "Madagaskar" },
  { code: "MH", flag: "🇲🇭", es: "Islas Marshall", en: "Marshall Islands", ca: "Illes Marshall", fr: "Îles Marshall", de: "Marshallinseln", it: "Isole Marshall", nl: "Marshalleilanden" },
  { code: "MK", flag: "🇲🇰", es: "Macedonia del Norte", en: "North Macedonia", ca: "Macedònia del Nord", fr: "Macédoine du Nord", de: "Nordmazedonien", it: "Macedonia del Nord", nl: "Noord-Macedonië" },
  { code: "ML", flag: "🇲🇱", es: "Mali", en: "Mali", ca: "Mali", fr: "Mali", de: "Mali", it: "Mali", nl: "Mali" },
  { code: "MM", flag: "🇲🇲", es: "Myanmar (Birmania)", en: "Myanmar (Burma)", ca: "Myanmar (Birmània)", fr: "Myanmar (Birmanie)", de: "Myanmar", it: "Myanmar (Birmania)", nl: "Myanmar (Birma)" },
  { code: "MN", flag: "🇲🇳", es: "Mongolia", en: "Mongolia", ca: "Mongòlia", fr: "Mongolie", de: "Mongolei", it: "Mongolia", nl: "Mongolië" },
  { code: "MO", flag: "🇲🇴", es: "RAE de Macao (China)", en: "Macao SAR China", ca: "Macau (RAE Xina)", fr: "R.A.S. chinoise de Macao", de: "Sonderverwaltungsregion Macau", it: "RAS di Macao", nl: "Macau SAR van China" },
  { code: "MP", flag: "🇲🇵", es: "Islas Marianas del Norte", en: "Northern Mariana Islands", ca: "Illes Mariannes del Nord", fr: "Îles Mariannes du Nord", de: "Nördliche Marianen", it: "Isole Marianne settentrionali", nl: "Noordelijke Marianen" },
  { code: "MQ", flag: "🇲🇶", es: "Martinica", en: "Martinique", ca: "Martinica", fr: "Martinique", de: "Martinique", it: "Martinica", nl: "Martinique" },
  { code: "MR", flag: "🇲🇷", es: "Mauritania", en: "Mauritania", ca: "Mauritània", fr: "Mauritanie", de: "Mauretanien", it: "Mauritania", nl: "Mauritanië" },
  { code: "MS", flag: "🇲🇸", es: "Montserrat", en: "Montserrat", ca: "Montserrat", fr: "Montserrat", de: "Montserrat", it: "Montserrat", nl: "Montserrat" },
  { code: "MT", flag: "🇲🇹", es: "Malta", en: "Malta", ca: "Malta", fr: "Malte", de: "Malta", it: "Malta", nl: "Malta" },
  { code: "MU", flag: "🇲🇺", es: "Mauricio", en: "Mauritius", ca: "Maurici", fr: "Maurice", de: "Mauritius", it: "Mauritius", nl: "Mauritius" },
  { code: "MV", flag: "🇲🇻", es: "Maldivas", en: "Maldives", ca: "Maldives", fr: "Maldives", de: "Malediven", it: "Maldive", nl: "Maldiven" },
  { code: "MW", flag: "🇲🇼", es: "Malaui", en: "Malawi", ca: "Malawi", fr: "Malawi", de: "Malawi", it: "Malawi", nl: "Malawi" },
  { code: "MX", flag: "🇲🇽", es: "México", en: "Mexico", ca: "Mèxic", fr: "Mexique", de: "Mexiko", it: "Messico", nl: "Mexico" },
  { code: "MY", flag: "🇲🇾", es: "Malasia", en: "Malaysia", ca: "Malàisia", fr: "Malaisie", de: "Malaysia", it: "Malaysia", nl: "Maleisië" },
  { code: "MZ", flag: "🇲🇿", es: "Mozambique", en: "Mozambique", ca: "Moçambic", fr: "Mozambique", de: "Mosambik", it: "Mozambico", nl: "Mozambique" },
  { code: "NA", flag: "🇳🇦", es: "Namibia", en: "Namibia", ca: "Namíbia", fr: "Namibie", de: "Namibia", it: "Namibia", nl: "Namibië" },
  { code: "NC", flag: "🇳🇨", es: "Nueva Caledonia", en: "New Caledonia", ca: "Nova Caledònia", fr: "Nouvelle-Calédonie", de: "Neukaledonien", it: "Nuova Caledonia", nl: "Nieuw-Caledonië" },
  { code: "NE", flag: "🇳🇪", es: "Níger", en: "Niger", ca: "Níger", fr: "Niger", de: "Niger", it: "Niger", nl: "Niger" },
  { code: "NF", flag: "🇳🇫", es: "Isla Norfolk", en: "Norfolk Island", ca: "Norfolk", fr: "Île Norfolk", de: "Norfolkinsel", it: "Isola Norfolk", nl: "Norfolk" },
  { code: "NG", flag: "🇳🇬", es: "Nigeria", en: "Nigeria", ca: "Nigèria", fr: "Nigéria", de: "Nigeria", it: "Nigeria", nl: "Nigeria" },
  { code: "NI", flag: "🇳🇮", es: "Nicaragua", en: "Nicaragua", ca: "Nicaragua", fr: "Nicaragua", de: "Nicaragua", it: "Nicaragua", nl: "Nicaragua" },
  { code: "NL", flag: "🇳🇱", es: "Países Bajos", en: "Netherlands", ca: "Països Baixos", fr: "Pays-Bas", de: "Niederlande", it: "Paesi Bassi", nl: "Nederland" },
  { code: "NO", flag: "🇳🇴", es: "Noruega", en: "Norway", ca: "Noruega", fr: "Norvège", de: "Norwegen", it: "Norvegia", nl: "Noorwegen" },
  { code: "NP", flag: "🇳🇵", es: "Nepal", en: "Nepal", ca: "Nepal", fr: "Népal", de: "Nepal", it: "Nepal", nl: "Nepal" },
  { code: "NR", flag: "🇳🇷", es: "Nauru", en: "Nauru", ca: "Nauru", fr: "Nauru", de: "Nauru", it: "Nauru", nl: "Nauru" },
  { code: "NU", flag: "🇳🇺", es: "Niue", en: "Niue", ca: "Niue", fr: "Niue", de: "Niue", it: "Niue", nl: "Niue" },
  { code: "NZ", flag: "🇳🇿", es: "Nueva Zelanda", en: "New Zealand", ca: "Nova Zelanda", fr: "Nouvelle-Zélande", de: "Neuseeland", it: "Nuova Zelanda", nl: "Nieuw-Zeeland" },
  { code: "OM", flag: "🇴🇲", es: "Omán", en: "Oman", ca: "Oman", fr: "Oman", de: "Oman", it: "Oman", nl: "Oman" },
  { code: "PA", flag: "🇵🇦", es: "Panamá", en: "Panama", ca: "Panamà", fr: "Panama", de: "Panama", it: "Panamá", nl: "Panama" },
  { code: "PE", flag: "🇵🇪", es: "Perú", en: "Peru", ca: "Perú", fr: "Pérou", de: "Peru", it: "Perù", nl: "Peru" },
  { code: "PF", flag: "🇵🇫", es: "Polinesia Francesa", en: "French Polynesia", ca: "Polinèsia Francesa", fr: "Polynésie française", de: "Französisch-Polynesien", it: "Polinesia francese", nl: "Frans-Polynesië" },
  { code: "PG", flag: "🇵🇬", es: "Papúa Nueva Guinea", en: "Papua New Guinea", ca: "Papua Nova Guinea", fr: "Papouasie-Nouvelle-Guinée", de: "Papua-Neuguinea", it: "Papua Nuova Guinea", nl: "Papoea-Nieuw-Guinea" },
  { code: "PH", flag: "🇵🇭", es: "Filipinas", en: "Philippines", ca: "Filipines", fr: "Philippines", de: "Philippinen", it: "Filippine", nl: "Filipijnen" },
  { code: "PK", flag: "🇵🇰", es: "Pakistán", en: "Pakistan", ca: "Pakistan", fr: "Pakistan", de: "Pakistan", it: "Pakistan", nl: "Pakistan" },
  { code: "PL", flag: "🇵🇱", es: "Polonia", en: "Poland", ca: "Polònia", fr: "Pologne", de: "Polen", it: "Polonia", nl: "Polen" },
  { code: "PM", flag: "🇵🇲", es: "San Pedro y Miquelón", en: "St. Pierre & Miquelon", ca: "Saint-Pierre-et-Miquelon", fr: "Saint-Pierre-et-Miquelon", de: "St. Pierre und Miquelon", it: "Saint-Pierre e Miquelon", nl: "Saint-Pierre en Miquelon" },
  { code: "PN", flag: "🇵🇳", es: "Islas Pitcairn", en: "Pitcairn Islands", ca: "Illes Pitcairn", fr: "Îles Pitcairn", de: "Pitcairninseln", it: "Isole Pitcairn", nl: "Pitcairneilanden" },
  { code: "PR", flag: "🇵🇷", es: "Puerto Rico", en: "Puerto Rico", ca: "Puerto Rico", fr: "Porto Rico", de: "Puerto Rico", it: "Portorico", nl: "Puerto Rico" },
  { code: "PS", flag: "🇵🇸", es: "Territorios Palestinos", en: "Palestinian Territories", ca: "Territoris palestins", fr: "Territoires palestiniens", de: "Palästinensische Autonomiegebiete", it: "Territori palestinesi", nl: "Palestijnse gebieden" },
  { code: "PT", flag: "🇵🇹", es: "Portugal", en: "Portugal", ca: "Portugal", fr: "Portugal", de: "Portugal", it: "Portogallo", nl: "Portugal" },
  { code: "PW", flag: "🇵🇼", es: "Palaos", en: "Palau", ca: "Palau", fr: "Palaos", de: "Palau", it: "Palau", nl: "Palau" },
  { code: "PY", flag: "🇵🇾", es: "Paraguay", en: "Paraguay", ca: "Paraguai", fr: "Paraguay", de: "Paraguay", it: "Paraguay", nl: "Paraguay" },
  { code: "QA", flag: "🇶🇦", es: "Catar", en: "Qatar", ca: "Qatar", fr: "Qatar", de: "Katar", it: "Qatar", nl: "Qatar" },
  { code: "RE", flag: "🇷🇪", es: "Reunión", en: "Réunion", ca: "Illa de la Reunió", fr: "La Réunion", de: "Réunion", it: "Riunione", nl: "Réunion" },
  { code: "RO", flag: "🇷🇴", es: "Rumanía", en: "Romania", ca: "Romania", fr: "Roumanie", de: "Rumänien", it: "Romania", nl: "Roemenië" },
  { code: "RS", flag: "🇷🇸", es: "Serbia", en: "Serbia", ca: "Sèrbia", fr: "Serbie", de: "Serbien", it: "Serbia", nl: "Servië" },
  { code: "RU", flag: "🇷🇺", es: "Rusia", en: "Russia", ca: "Rússia", fr: "Russie", de: "Russland", it: "Russia", nl: "Rusland" },
  { code: "RW", flag: "🇷🇼", es: "Ruanda", en: "Rwanda", ca: "Ruanda", fr: "Rwanda", de: "Ruanda", it: "Ruanda", nl: "Rwanda" },
  { code: "SA", flag: "🇸🇦", es: "Arabia Saudí", en: "Saudi Arabia", ca: "Aràbia Saudita", fr: "Arabie saoudite", de: "Saudi-Arabien", it: "Arabia Saudita", nl: "Saoedi-Arabië" },
  { code: "SB", flag: "🇸🇧", es: "Islas Salomón", en: "Solomon Islands", ca: "Illes Salomó", fr: "Îles Salomon", de: "Salomonen", it: "Isole Salomone", nl: "Salomonseilanden" },
  { code: "SC", flag: "🇸🇨", es: "Seychelles", en: "Seychelles", ca: "Seychelles", fr: "Seychelles", de: "Seychellen", it: "Seychelles", nl: "Seychellen" },
  { code: "SD", flag: "🇸🇩", es: "Sudán", en: "Sudan", ca: "Sudan", fr: "Soudan", de: "Sudan", it: "Sudan", nl: "Soedan" },
  { code: "SE", flag: "🇸🇪", es: "Suecia", en: "Sweden", ca: "Suècia", fr: "Suède", de: "Schweden", it: "Svezia", nl: "Zweden" },
  { code: "SG", flag: "🇸🇬", es: "Singapur", en: "Singapore", ca: "Singapur", fr: "Singapour", de: "Singapur", it: "Singapore", nl: "Singapore" },
  { code: "SH", flag: "🇸🇭", es: "Santa Elena", en: "St. Helena", ca: "Saint Helena", fr: "Sainte-Hélène", de: "St. Helena", it: "Sant’Elena", nl: "Sint-Helena" },
  { code: "SI", flag: "🇸🇮", es: "Eslovenia", en: "Slovenia", ca: "Eslovènia", fr: "Slovénie", de: "Slowenien", it: "Slovenia", nl: "Slovenië" },
  { code: "SJ", flag: "🇸🇯", es: "Svalbard y Jan Mayen", en: "Svalbard & Jan Mayen", ca: "Svalbard i Jan Mayen", fr: "Svalbard et Jan Mayen", de: "Spitzbergen und Jan Mayen", it: "Svalbard e Jan Mayen", nl: "Spitsbergen en Jan Mayen" },
  { code: "SK", flag: "🇸🇰", es: "Eslovaquia", en: "Slovakia", ca: "Eslovàquia", fr: "Slovaquie", de: "Slowakei", it: "Slovacchia", nl: "Slowakije" },
  { code: "SL", flag: "🇸🇱", es: "Sierra Leona", en: "Sierra Leone", ca: "Sierra Leone", fr: "Sierra Leone", de: "Sierra Leone", it: "Sierra Leone", nl: "Sierra Leone" },
  { code: "SM", flag: "🇸🇲", es: "San Marino", en: "San Marino", ca: "San Marino", fr: "Saint-Marin", de: "San Marino", it: "San Marino", nl: "San Marino" },
  { code: "SN", flag: "🇸🇳", es: "Senegal", en: "Senegal", ca: "Senegal", fr: "Sénégal", de: "Senegal", it: "Senegal", nl: "Senegal" },
  { code: "SO", flag: "🇸🇴", es: "Somalia", en: "Somalia", ca: "Somàlia", fr: "Somalie", de: "Somalia", it: "Somalia", nl: "Somalië" },
  { code: "SR", flag: "🇸🇷", es: "Surinam", en: "Suriname", ca: "Surinam", fr: "Suriname", de: "Suriname", it: "Suriname", nl: "Suriname" },
  { code: "SS", flag: "🇸🇸", es: "Sudán del Sur", en: "South Sudan", ca: "Sudan del Sud", fr: "Soudan du Sud", de: "Südsudan", it: "Sud Sudan", nl: "Zuid-Soedan" },
  { code: "ST", flag: "🇸🇹", es: "Santo Tomé y Príncipe", en: "São Tomé & Príncipe", ca: "São Tomé i Príncipe", fr: "Sao Tomé-et-Principe", de: "São Tomé und Príncipe", it: "São Tomé e Príncipe", nl: "Sao Tomé en Principe" },
  { code: "SV", flag: "🇸🇻", es: "El Salvador", en: "El Salvador", ca: "El Salvador", fr: "Salvador", de: "El Salvador", it: "El Salvador", nl: "El Salvador" },
  { code: "SX", flag: "🇸🇽", es: "Sint Maarten", en: "Sint Maarten", ca: "Sint Maarten", fr: "Saint-Martin (partie néerlandaise)", de: "Sint Maarten", it: "Sint Maarten", nl: "Sint-Maarten" },
  { code: "SY", flag: "🇸🇾", es: "Siria", en: "Syria", ca: "Síria", fr: "Syrie", de: "Syrien", it: "Siria", nl: "Syrië" },
  { code: "SZ", flag: "🇸🇿", es: "Esuatini", en: "Eswatini", ca: "eSwatini", fr: "Eswatini", de: "Eswatini", it: "Swaziland", nl: "eSwatini" },
  { code: "TC", flag: "🇹🇨", es: "Islas Turcas y Caicos", en: "Turks & Caicos Islands", ca: "Illes Turks i Caicos", fr: "Îles Turques-et-Caïques", de: "Turks- und Caicosinseln", it: "Isole Turks e Caicos", nl: "Turks- en Caicoseilanden" },
  { code: "TD", flag: "🇹🇩", es: "Chad", en: "Chad", ca: "Txad", fr: "Tchad", de: "Tschad", it: "Ciad", nl: "Tsjaad" },
  { code: "TF", flag: "🇹🇫", es: "Territorios Australes Franceses", en: "French Southern Territories", ca: "Territoris Australs Francesos", fr: "Terres australes françaises", de: "Französische Süd- und Antarktisgebiete", it: "Terre australi francesi", nl: "Franse Gebieden in de zuidelijke Indische Oceaan" },
  { code: "TG", flag: "🇹🇬", es: "Togo", en: "Togo", ca: "Togo", fr: "Togo", de: "Togo", it: "Togo", nl: "Togo" },
  { code: "TH", flag: "🇹🇭", es: "Tailandia", en: "Thailand", ca: "Tailàndia", fr: "Thaïlande", de: "Thailand", it: "Thailandia", nl: "Thailand" },
  { code: "TJ", flag: "🇹🇯", es: "Tayikistán", en: "Tajikistan", ca: "Tadjikistan", fr: "Tadjikistan", de: "Tadschikistan", it: "Tagikistan", nl: "Tadzjikistan" },
  { code: "TK", flag: "🇹🇰", es: "Tokelau", en: "Tokelau", ca: "Tokelau", fr: "Tokelau", de: "Tokelau", it: "Tokelau", nl: "Tokelau" },
  { code: "TL", flag: "🇹🇱", es: "Timor-Leste", en: "Timor-Leste", ca: "Timor Oriental", fr: "Timor oriental", de: "Timor-Leste", it: "Timor Est", nl: "Oost-Timor" },
  { code: "TM", flag: "🇹🇲", es: "Turkmenistán", en: "Turkmenistan", ca: "Turkmenistan", fr: "Turkménistan", de: "Turkmenistan", it: "Turkmenistan", nl: "Turkmenistan" },
  { code: "TN", flag: "🇹🇳", es: "Túnez", en: "Tunisia", ca: "Tunísia", fr: "Tunisie", de: "Tunesien", it: "Tunisia", nl: "Tunesië" },
  { code: "TO", flag: "🇹🇴", es: "Tonga", en: "Tonga", ca: "Tonga", fr: "Tonga", de: "Tonga", it: "Tonga", nl: "Tonga" },
  { code: "TR", flag: "🇹🇷", es: "Turquía", en: "Turkey", ca: "Turquia", fr: "Turquie", de: "Türkei", it: "Turchia", nl: "Turkije" },
  { code: "TT", flag: "🇹🇹", es: "Trinidad y Tobago", en: "Trinidad & Tobago", ca: "Trinitat i Tobago", fr: "Trinité-et-Tobago", de: "Trinidad und Tobago", it: "Trinidad e Tobago", nl: "Trinidad en Tobago" },
  { code: "TV", flag: "🇹🇻", es: "Tuvalu", en: "Tuvalu", ca: "Tuvalu", fr: "Tuvalu", de: "Tuvalu", it: "Tuvalu", nl: "Tuvalu" },
  { code: "TW", flag: "🇹🇼", es: "Taiwán", en: "Taiwan", ca: "Taiwan", fr: "Taïwan", de: "Taiwan", it: "Taiwan", nl: "Taiwan" },
  { code: "TZ", flag: "🇹🇿", es: "Tanzania", en: "Tanzania", ca: "Tanzània", fr: "Tanzanie", de: "Tansania", it: "Tanzania", nl: "Tanzania" },
  { code: "UA", flag: "🇺🇦", es: "Ucrania", en: "Ukraine", ca: "Ucraïna", fr: "Ukraine", de: "Ukraine", it: "Ucraina", nl: "Oekraïne" },
  { code: "UG", flag: "🇺🇬", es: "Uganda", en: "Uganda", ca: "Uganda", fr: "Ouganda", de: "Uganda", it: "Uganda", nl: "Oeganda" },
  { code: "UM", flag: "🇺🇲", es: "Islas menores alejadas de EE. UU.", en: "U.S. Outlying Islands", ca: "Illes Perifèriques Menors dels EUA", fr: "Îles mineures éloignées des États-Unis", de: "Amerikanische Überseeinseln", it: "Altre isole americane del Pacifico", nl: "Kleine afgelegen eilanden van de Verenigde Staten" },
  { code: "US", flag: "🇺🇸", es: "Estados Unidos", en: "United States", ca: "Estats Units", fr: "États-Unis", de: "Vereinigte Staaten", it: "Stati Uniti", nl: "Verenigde Staten" },
  { code: "UY", flag: "🇺🇾", es: "Uruguay", en: "Uruguay", ca: "Uruguai", fr: "Uruguay", de: "Uruguay", it: "Uruguay", nl: "Uruguay" },
  { code: "UZ", flag: "🇺🇿", es: "Uzbekistán", en: "Uzbekistan", ca: "Uzbekistan", fr: "Ouzbékistan", de: "Usbekistan", it: "Uzbekistan", nl: "Oezbekistan" },
  { code: "VA", flag: "🇻🇦", es: "Ciudad del Vaticano", en: "Vatican City", ca: "Ciutat del Vaticà", fr: "État de la Cité du Vatican", de: "Vatikanstadt", it: "Città del Vaticano", nl: "Vaticaanstad" },
  { code: "VC", flag: "🇻🇨", es: "San Vicente y las Granadinas", en: "St. Vincent & Grenadines", ca: "Saint Vincent i les Grenadines", fr: "Saint-Vincent-et-les-Grenadines", de: "St. Vincent und die Grenadinen", it: "Saint Vincent e Grenadine", nl: "Saint Vincent en de Grenadines" },
  { code: "VE", flag: "🇻🇪", es: "Venezuela", en: "Venezuela", ca: "Veneçuela", fr: "Venezuela", de: "Venezuela", it: "Venezuela", nl: "Venezuela" },
  { code: "VG", flag: "🇻🇬", es: "Islas Vírgenes Británicas", en: "British Virgin Islands", ca: "Illes Verges Britàniques", fr: "Îles Vierges britanniques", de: "Britische Jungferninseln", it: "Isole Vergini Britanniche", nl: "Britse Maagdeneilanden" },
  { code: "VI", flag: "🇻🇮", es: "Islas Vírgenes de EE. UU.", en: "U.S. Virgin Islands", ca: "Illes Verges Nord-americanes", fr: "Îles Vierges des États-Unis", de: "Amerikanische Jungferninseln", it: "Isole Vergini Americane", nl: "Amerikaanse Maagdeneilanden" },
  { code: "VN", flag: "🇻🇳", es: "Vietnam", en: "Vietnam", ca: "Vietnam", fr: "Vietnam", de: "Vietnam", it: "Vietnam", nl: "Vietnam" },
  { code: "VU", flag: "🇻🇺", es: "Vanuatu", en: "Vanuatu", ca: "Vanuatu", fr: "Vanuatu", de: "Vanuatu", it: "Vanuatu", nl: "Vanuatu" },
  { code: "WF", flag: "🇼🇫", es: "Wallis y Futuna", en: "Wallis & Futuna", ca: "Wallis i Futuna", fr: "Wallis-et-Futuna", de: "Wallis und Futuna", it: "Wallis e Futuna", nl: "Wallis en Futuna" },
  { code: "WS", flag: "🇼🇸", es: "Samoa", en: "Samoa", ca: "Samoa", fr: "Samoa", de: "Samoa", it: "Samoa", nl: "Samoa" },
  { code: "YE", flag: "🇾🇪", es: "Yemen", en: "Yemen", ca: "Iemen", fr: "Yémen", de: "Jemen", it: "Yemen", nl: "Jemen" },
  { code: "YT", flag: "🇾🇹", es: "Mayotte", en: "Mayotte", ca: "Mayotte", fr: "Mayotte", de: "Mayotte", it: "Mayotte", nl: "Mayotte" },
  { code: "ZA", flag: "🇿🇦", es: "Sudáfrica", en: "South Africa", ca: "República de Sud-àfrica", fr: "Afrique du Sud", de: "Südafrika", it: "Sudafrica", nl: "Zuid-Afrika" },
  { code: "ZM", flag: "🇿🇲", es: "Zambia", en: "Zambia", ca: "Zàmbia", fr: "Zambie", de: "Sambia", it: "Zambia", nl: "Zambia" },
  { code: "ZW", flag: "🇿🇼", es: "Zimbabue", en: "Zimbabwe", ca: "Zimbàbue", fr: "Zimbabwe", de: "Simbabwe", it: "Zimbabwe", nl: "Zimbabwe" },
]

// Devuelve la lista ordenada alfabéticamente en el idioma dado (con España siempre
// primero, porque es con diferencia el país de origen más común entre los usuarios de
// Noctua). El valor guardado en base de datos sigue siendo el nombre en español, para
// no romper lo que ya hay guardado — esto solo cambia lo que se muestra en el desplegable.
export function getSortedCountries(locale: CountryLocale): Country[] {
  const spain = COUNTRIES.find((c) => c.code === "ES")!
  const rest = COUNTRIES.filter((c) => c.code !== "ES").sort((a, b) => a[locale].localeCompare(b[locale], locale))
  return [spain, ...rest]
}

